pages:
  stage: deploy
  script:
    # Copy whole project to the public path
    - mkdir .public
    - cp -r * .public
    - mv .public public
    
  artifacts:
    paths:
      - public
  only:
    - master